# StarGate Atlantis
# Project by Alemiz
# Website: https://github.com/Alemiz112

# Supports more connections
connections:
  lobby1:
    address: 192.168.0.50
    port: 47007
    password: 123456789

# Interval in ticks to receive data from connection
# Lower interval, faster packet decoding and encoding
tickInterval: 2
# Default client will be used if no clientName specified in api functions
defaultClient: "lobby1"