#StarGate Atlantis
##Project by Alemiz
#Website: https://github.com/Alemiz112

#Supports more connections
connections:
  default:
    address: 192.168.0.50
    port: 47007
    password: 123456789
    name: Lobby

#Interval in ticks to receive data from connection
TickInterval: 2